# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='catalog',
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
    ]
